POST http://localhost:4000/users/signup
Content-Type: application/json

{
    "name": "Asad",
    "email": "fahad12349@yopmail.com",
    "password": "asadasad"
}

###
GET http://localhost:4000/users/dashboard

###
POST http://localhost:4000/users/signin
Content-Type: application/json

{
    "email": "fahad12349@yopmail.com",
    "password": "asadasad"
}

###
GET http://localhost:4000/users/logout

###
GET http://localhost:4000/users/authenticationstatus

###
GET http://localhost:4000/data/partners